export const allTeams = {
  ANA: { abbrev: "ANA", name: "Anaheim Ducks", division: "Pacific" },
  ARI: { abbrev: "ARI", name: "Arizona Coyotes", division: "Central" },
  BOS: { abbrev: "BOS", name: "Boston Bruins", division: "Atlantic" },
  BUF: { abbrev: "BUF", name: "Buffalo Sabres", division: "Atlantic" },
  CAR: { abbrev: "CAR", name: "Carolina Hurricanes", division: "Metropolitan" },
  CBJ: {
    abbrev: "CBJ",
    name: "Columbus Blue Jackets",
    division: "Metropolitan",
  },
  CGY: { abbrev: "CGY", name: "Calgary Flames", division: "Pacific" },
  CHI: { abbrev: "CHI", name: "Chicago Blackhawks", division: "Central" },
  COL: { abbrev: "COL", name: "Colorado Avalanche", division: "Central" },
  DAL: { abbrev: "DAL", name: "Dallas Stars", division: "Central" },
  DET: { abbrev: "DET", name: "Detroit Red Wings", division: "Atlantic" },
  EDM: { abbrev: "EDM", name: "Edmonton Oilers", division: "Pacific" },
  FLA: { abbrev: "FLA", name: "Florida Panthers", division: "Atlantic" },
  LAK: { abbrev: "LAK", name: "Los Angeles Kings", division: "Pacific" },
  MIN: { abbrev: "MIN", name: "Minnesota Wild", division: "Central" },
  MTL: { abbrev: "MTL", name: "Montréal Canadiens", division: "Atlantic" },
  NJD: { abbrev: "NJD", name: "New Jersey Devils", division: "Metropolitan" },
  NSH: { abbrev: "NSH", name: "Nashville Predators", division: "Central" },
  NYI: { abbrev: "NYI", name: "New York Islanders", division: "Metropolitan" },
  NYR: { abbrev: "NYR", name: "New York Rangers", division: "Metropolitan" },
  OTT: { abbrev: "OTT", name: "Ottawa Senators", division: "Atlantic" },
  PHI: { abbrev: "PHI", name: "Philadelphia Flyers", division: "Metropolitan" },
  PIT: { abbrev: "PIT", name: "Pittsburgh Penguins", division: "Metropolitan" },
  SEA: { abbrev: "SEA", name: "Seattle Kraken", division: "Pacific" },
  SJS: { abbrev: "SJS", name: "San Jose Sharks", division: "Pacific" },
  STL: { abbrev: "STL", name: "St. Louis Blues", division: "Central" },
  TBL: { abbrev: "TBL", name: "Tampa Bay Lightning", division: "Atlantic" },
  TOR: { abbrev: "TOR", name: "Toronto Maple Leafs", division: "Atlantic" },
  UTA: { abbrev: "UTA", name: "Utah Mammoth", division: "Central" },
  VAN: { abbrev: "VAN", name: "Vancouver Canucks", division: "Pacific" },
  VGK: { abbrev: "VGK", name: "Vegas Golden Knights", division: "Pacific" },
  WPG: { abbrev: "WPG", name: "Winnipeg Jets", division: "Central" },
  WSH: { abbrev: "WSH", name: "Washington Capitals", division: "Metropolitan" },
};
